# Generated by Django 5.2.15 on 2026-06-15 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("family", models.CharField(max_length=100)),
                ("mellinumber", models.IntegerField(max_length=100, unique=True)),
                ("address", models.TextField()),
                ("birthday", models.DateField()),
            ],
        ),
    ]
