# Generated by Django 5.2.15 on 2026-06-22 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="mellinumber",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
