# Generated by Django 5.2.15 on 2026-06-22 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0002_alter_person_mellinumber"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="mellinumber",
            field=models.CharField(max_length=100),
        ),
    ]
